### ISSUE TITLE
Missing pkc() and plc() Functions Prevent Compilation

### ISSUE THREAD

**Issue by alanSquirrelyz** [GearlessL/PDC#1]
Hi,

I tried running the graphs using your code, but it fails to compile due to the absence of the `pkc()` and `plc()` functions. I’m unsure if I made a mistake or if these functions are missing in the current version. Could you confirm if they are intentionally excluded or provide guidance on resolving this issue?

Here is the output:
```
❯ g++ -std=c++17 -fopenmp ./src/*.cpp -o dcore
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: /tmp/cc1LGLiX.o: in function `Graph::Shell_PDC()':
Graph.cpp:(.text+0x390f): undefined reference to `Graph::pkc()'
/opt/rh/gcc-toolset-13/root/usr/libexec/gcc/x86_64-redhat-linux/13/ld: Graph.cpp:(.text+0x3936): undefined reference to `Graph::plc()'
collect2: error: ld returned 1 exit status
```
Thanks!

**Comment by GearlessL** [comment]
Sorry for the oversight. We have just updated the code and added these two functions.
